locals { services=toset(["run.googleapis.com","artifactregistry.googleapis.com","cloudkms.googleapis.com","secretmanager.googleapis.com","cloudscheduler.googleapis.com","iamcredentials.googleapis.com","cloudbuild.googleapis.com"]) }
resource "google_project_service" "apis" { for_each=local.services service=each.value disable_on_destroy=false }
resource "google_service_account" "runtime" { account_id="inbox-keeper-staging" display_name="Inbox Keeper staging runtime" }
resource "google_service_account" "tasks" { account_id="inbox-keeper-tasks" display_name="Inbox Keeper task caller" }
resource "google_artifact_registry_repository" "images" { location=var.region repository_id="inbox-keeper" format="DOCKER" depends_on=[google_project_service.apis] }
resource "google_kms_key_ring" "tokens" { name="inbox-keeper-staging" location=var.region depends_on=[google_project_service.apis] }
resource "google_kms_crypto_key" "tokens" { name="gmail-token-envelopes" key_ring=google_kms_key_ring.tokens.id rotation_period="7776000s" lifecycle { prevent_destroy=true } }
resource "google_kms_crypto_key_iam_member" "runtime" { crypto_key_id=google_kms_crypto_key.tokens.id role="roles/cloudkms.cryptoKeyEncrypterDecrypter" member="serviceAccount:${google_service_account.runtime.email}" }
resource "google_secret_manager_secret_iam_member" "db" { secret_id=split("/",var.database_url_secret_version)[3] role="roles/secretmanager.secretAccessor" member="serviceAccount:${google_service_account.runtime.email}" }
resource "google_secret_manager_secret_iam_member" "oauth" { secret_id=split("/",var.gmail_client_secret_version)[3] role="roles/secretmanager.secretAccessor" member="serviceAccount:${google_service_account.runtime.email}" }
resource "google_cloud_run_v2_service" "app" { name="inbox-keeper-staging" location=var.region ingress="INGRESS_TRAFFIC_ALL" deletion_protection=true template { service_account=google_service_account.runtime.email timeout="60s" max_instance_request_concurrency=20 scaling { min_instance_count=0 max_instance_count=2 } containers { image=var.container_image ports { container_port=8080 } env { name="NODE_ENV" value="production" } env { name="GMAIL_LIVE_MODE" value="enabled" } env { name="APP_ORIGIN" value="https://${var.staging_domain}" } env { name="GMAIL_REDIRECT_URI" value="https://${var.staging_domain}/api/oauth/callback" } env { name="GMAIL_CLIENT_ID" value=var.gmail_client_id } env { name="GMAIL_CLIENT_SECRET_RESOURCE" value=var.gmail_client_secret_version } env { name="DATABASE_URL" value_source { secret_key_ref { secret=split("/",var.database_url_secret_version)[3] version=split("/",var.database_url_secret_version)[5] } } } env { name="GCP_KMS_KEY_NAME" value=google_kms_crypto_key.tokens.id } env { name="CLOUD_TASKS_AUDIENCE" value="https://${var.staging_domain}" } env { name="CLOUD_TASKS_SERVICE_ACCOUNT" value=google_service_account.tasks.email } startup_probe { http_get { path="/readyz" } failure_threshold=12 period_seconds=5 } liveness_probe { http_get { path="/healthz" } period_seconds=30 } } } depends_on=[google_project_service.apis] }
resource "google_cloud_run_v2_service_iam_member" "task_invoker" { name=google_cloud_run_v2_service.app.name location=var.region role="roles/run.invoker" member="serviceAccount:${google_service_account.tasks.email}" }
resource "google_cloud_run_v2_service_iam_member" "public_web" { name=google_cloud_run_v2_service.app.name location=var.region role="roles/run.invoker" member="allUsers" }
resource "google_cloud_scheduler_job" "reconcile" { name="gmail-reconcile" region=var.region schedule="*/5 * * * *" time_zone="Etc/UTC" http_target { http_method="POST" uri="https://${var.staging_domain}/internal/tasks/reconcile" oidc_token { service_account_email=google_service_account.tasks.email audience="https://${var.staging_domain}" } } }
