import{createServer}from'node:http';import{randomUUID}from'node:crypto';import{CleanupService}from'./jobs.js';import{DisabledGmailProvider,MockGmailProvider}from'./mock-provider.js';import{SqliteStore}from'./store.js';import{DurableJobs}from'./durable-jobs.js';import{jsonBody,PublicError,requireMutation,requireSession,send,sessionCookie}from'./http-security.js';import{BoundedQueue,SlidingLimit}from'./limits.js';import{PreviewService}from'./preview-service.js';import{authorizationUrl,opaqueState,pkce}from'./security.js';import{DisabledGoogleOAuth}from'./google-adapter.js';
const live=process.env.GMAIL_LIVE_MODE==='enabled',production=process.env.NODE_ENV==='production',dbPath=process.env.INBOX_DB_PATH||':memory:';
if(production&&dbPath===':memory:')throw new Error('Production requires a durable database. Refusing in-memory startup.');
if(live)throw new Error('Live Gmail requires the separately configured KMS-backed runtime. This safe entrypoint refuses live startup.');
const origin=process.env.APP_ORIGIN||'http://127.0.0.1:5173',store=new SqliteStore(dbPath),provider=live?new DisabledGmailProvider():new MockGmailProvider(),oauth=new DisabledGoogleOAuth(),previews=new PreviewService(provider,store),globalLimit=new SlidingLimit(200,60_000),userLimit=new SlidingLimit(60,60_000),queue=new BoundedQueue(2,50);
const server=createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');const requestId=randomUUID();try{globalLimit.check('global');
 if(req.method==='GET'&&req.url==='/healthz')return send(res,200,{ok:true,mode:'local-demo'});
 if(req.method==='GET'&&req.url==='/readyz')return send(res,200,{ok:true,mode:'local-demo',liveGmail:false});
 if(req.method==='POST'&&req.url==='/api/session'){if(req.headers.origin!==origin)throw new PublicError(403,'Request origin rejected');const s=store.createSession();res.setHeader('Set-Cookie',sessionCookie(s.id,production));return send(res,201,{csrfToken:s.csrf,expiresAt:s.expiresAt,mode:live?'disconnected':'demo'})}
 const session=requireSession(req,store);if(!session)throw new PublicError(401,'Session required');userLimit.check(session.userId);
 if(req.method==='GET'&&req.url==='/api/status')return send(res,200,{mode:live?'disconnected':'demo',liveEnabled:live,provider:provider.kind,scopes:[],csrfToken:session.csrf});
 if(req.method==='POST'&&req.url==='/api/sync'){requireMutation(req,session,origin);const page=await provider.listMetadata();for(const message of page.items)store.putMetadata(session.userId,message);return send(res,200,{messages:page.items,nextPageToken:page.nextPageToken})}
 if(req.method==='GET'&&req.url==='/api/messages')return send(res,200,{messages:store.metadata(session.userId)});
 if(req.method==='POST'&&req.url==='/api/oauth/start'){requireMutation(req,session,origin);if(!live)throw new PublicError(503,'Live Gmail is disabled');const body=await jsonBody(req),cleanup=body.cleanup===true,{verifier,challenge}=pkce(),state=opaqueState();store.bindOAuth(session.id,state,verifier);return send(res,200,{authorizationUrl:authorizationUrl({clientId:process.env.GMAIL_CLIENT_ID!,redirectUri:process.env.GMAIL_REDIRECT_URI!,state,challenge,cleanup})})}
 if(req.method==='GET'&&req.url?.startsWith('/api/oauth/callback')){const u=new URL(req.url,origin),state=u.searchParams.get('state')||'',code=u.searchParams.get('code')||'',verifier=store.consumeOAuth(session.id,state);if(!verifier||!code)throw new PublicError(400,'OAuth callback rejected');await oauth.exchangeCode({code,verifier,redirectUri:process.env.GMAIL_REDIRECT_URI!});const rotated=store.rotateSession(session.id)!;res.setHeader('Set-Cookie',sessionCookie(rotated.id,production));return send(res,200,{ok:true})}
 if(req.method==='PUT'&&req.url==='/api/protections'){requireMutation(req,session,origin);const b=await jsonBody(req);if(!Array.isArray(b.senders)||!Array.isArray(b.domains)||!Number.isSafeInteger(b.expectedVersion)||b.expectedVersion<0)throw new PublicError(400,'Invalid protection rules or version');const version=store.replaceProtections(session.userId,b.senders.map(String).slice(0,1000),b.domains.map(String).slice(0,1000),b.expectedVersion);if(version===null)throw new PublicError(409,'Protected mail changed in another session. Latest rules were reloaded; review and retry your change.');const rules=store.protections(session.userId);return send(res,200,{version,senders:[...rules.senders],domains:[...rules.domains]})}
 if(req.method==='POST'&&req.url==='/api/protections/senders'){requireMutation(req,session,origin);const b=await jsonBody(req);if(!Array.isArray(b.senders)||b.senders.length<1||b.senders.length>500)throw new PublicError(400,'Select between 1 and 500 senders');const senders:string[]=[...new Set<string>((b.senders as unknown[]).map(v=>String(v).trim().toLowerCase()).filter(v=>/^[^@\s]+@[^@\s]+$/.test(v)))];if(!senders.length)throw new PublicError(400,'No valid sender addresses');const version=store.addProtections(session.userId,senders),rules=store.protections(session.userId);return send(res,200,{version,senders:[...rules.senders],domains:[...rules.domains]})}
 if(req.method==='POST'&&req.url==='/api/previews'){requireMutation(req,session,origin);const b=await jsonBody(req);if(!Array.isArray(b.ids)||!['trash','restore'].includes(b.action))throw new PublicError(400,'Invalid preview');return send(res,201,await previews.create({sessionId:session.id,userId:session.userId,action:b.action,ids:b.ids.map(String)}))}
 if(req.method==='POST'&&req.url==='/api/jobs'){requireMutation(req,session,origin);const idempotency=String(req.headers['idempotency-key']||'');if(!idempotency||idempotency.length>128)throw new PublicError(400,'Valid Idempotency-Key required');const prior=store.job(idempotency,session.userId);if(prior)return send(res,200,prior);const b=await jsonBody(req),p=await previews.validate({previewId:String(b.previewId||''),sessionId:session.id,userId:session.userId,confirmation:b.confirmation});const service=new CleanupService(provider,new DurableJobs(store,session.userId)),out=await queue.run(()=>service.run({jobId:idempotency,action:p.action,ids:p.ids,protections:()=>store.protections(session.userId)}));return send(res,200,out)}
 if(req.method==='POST'&&req.url==='/api/disconnect'){requireMutation(req,session,origin);await oauth.revoke('unavailable').catch(()=>{});store.deleteUser(session.userId);res.setHeader('Set-Cookie',sessionCookie('',production).replace('Max-Age=1800','Max-Age=0'));return send(res,200,{ok:true,mode:'disconnected'})}
 if(req.method==='DELETE'&&req.url==='/api/account'){requireMutation(req,session,origin);store.deleteUser(session.userId);res.setHeader('Set-Cookie',sessionCookie('',production).replace('Max-Age=1800','Max-Age=0'));return send(res,200,{ok:true,deleted:['tokens','metadata','protections','previews','jobs','audit','sessions']})}
 throw new PublicError(404,'Not found');
 }catch(e){const status=e instanceof PublicError?e.status:500;send(res,status,{error:status>=500?'Request failed safely':e instanceof Error?e.message:'Request rejected',requestId})}});
server.listen(8787,'127.0.0.1',()=>console.log('Inbox Keeper BFF: http://127.0.0.1:8787 (live Gmail disabled by default)'));
