// @vitest-environment node
import{describe,expect,it}from'vitest';import{PreviewService}from'./preview-service.js';import{MockGmailProvider}from'./mock-provider.js';import{SqliteStore}from'./store.js';
const m=(id:string,address='a@x.com')=>({id,threadId:id,fromName:'A',fromAddress:address,subject:'s',receivedAt:new Date().toISOString(),sizeEstimate:1,labels:[],unread:false,starred:false,hasAttachment:false});
describe('server-owned previews',()=>{it('binds account/session, excludes protected and is one-use',async()=>{const store=new SqliteStore(),session=store.createSession('u');store.replaceProtections('u',[],['safe.com']);const service=new PreviewService(new MockGmailProvider([m('1'),m('2','b@safe.com')]),store),p=await service.create({sessionId:session.id,userId:'u',action:'trash',ids:['1','2']});expect(p.ids).toEqual(['1']);expect(p.excluded).toEqual(['2']);expect((await service.validate({previewId:p.id,sessionId:session.id,userId:'u'})).id).toBe(p.id);await expect(service.validate({previewId:p.id,sessionId:session.id,userId:'u'})).rejects.toThrow(/used/);store.close()});it('invalidates when protection version changes',async()=>{const store=new SqliteStore(),session=store.createSession('u'),service=new PreviewService(new MockGmailProvider([m('1')]),store),p=await service.create({sessionId:session.id,userId:'u',action:'trash',ids:['1']});store.replaceProtections('u',[],['new.com']);await expect(service.validate({previewId:p.id,sessionId:session.id,userId:'u'})).rejects.toThrow(/rules changed/);store.close()})});

it('rejects more than 500 requested messages instead of truncating',async()=>{const store=new SqliteStore(),session=store.createSession('u'),messages=Array.from({length:501},(_,i)=>m(String(i))),service=new PreviewService(new MockGmailProvider(messages),store);await expect(service.create({sessionId:session.id,userId:'u',action:'trash',ids:messages.map(x=>x.id)})).rejects.toThrow(/between 1 and 500/);store.close()});

it('requires the exact server-owned confirmation for large previews',async()=>{const store=new SqliteStore(),session=store.createSession('u'),messages=Array.from({length:50},(_,i)=>m(String(i))),service=new PreviewService(new MockGmailProvider(messages),store),preview=await service.create({sessionId:session.id,userId:'u',action:'trash',ids:messages.map(x=>x.id)});expect(preview.confirmText).toBe('MOVE 50');await expect(service.validate({previewId:preview.id,sessionId:session.id,userId:'u',confirmation:'move 50'})).rejects.toThrow(/does not match/);expect((await service.validate({previewId:preview.id,sessionId:session.id,userId:'u',confirmation:'MOVE 50'})).id).toBe(preview.id);store.close()});

it('atomically allows only one concurrent preview claim',async()=>{const store=new SqliteStore(),session=store.createSession('u'),service=new PreviewService(new MockGmailProvider([m('1')]),store),p=await service.create({sessionId:session.id,userId:'u',action:'trash',ids:['1']});const results=await Promise.allSettled([service.validate({previewId:p.id,sessionId:session.id,userId:'u'}),service.validate({previewId:p.id,sessionId:session.id,userId:'u'})]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(results.filter(r=>r.status==='rejected')).toHaveLength(1);store.close()});
