import type{ConnectionMode}from'./types';
export interface BffStatus{mode:ConnectionMode;liveEnabled:boolean;provider:'mock'|'gmail';scopes:string[];csrfToken:string;email?:string}
export interface GmailMetadata{id:string;threadId:string;fromName:string;fromAddress:string;subject:string;receivedAt:string;sizeEstimate:number;labels:string[];unread:boolean;starred:boolean;hasAttachment:boolean}
export interface JobResult{jobId:string;action:'trash'|'restore';items:Array<{id:string;status:'succeeded'|'skipped'|'unknown';reason?:string}>;succeeded:number;skipped:number;unknown:number}
export interface ServerPreview{previewId:string;action:'trash'|'restore';requestedCount:number;count:number;excludedCount:number;missingCount:number;confirmText:string;expiresInSeconds:number}
export interface ProtectionState{senders:string[];domains:string[];version:number}
export interface ServerAuditEvent{id:string;eventType:string;event:JobResult;createdAt:string}
export type EmailCategory='receipts'|'shipping'|'promotions'|'newsletters'|'statements'|'surveys'|'account'|'personal';
export interface CategoryDescriptor{key:EmailCategory;label:string;description:string;defaultProtected:boolean}
export interface BrandSummary{brandKey:string;displayName:string;isCustom:boolean;totalMessages:number;categories:Record<EmailCategory,number>;lastMessageAt:string;storageBytes:number;sampleSenders:string[]}
export interface BrandDetail{brandKey:string;displayName:string;isCustom:boolean;totalMessages:number;categories:Record<EmailCategory,GmailMetadata[]>}
let csrf='';
export class BffError extends Error{constructor(readonly status:number,message:string){super(message)}}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const response=await fetch(path,{...init,credentials:'same-origin',headers:{...(init.body?{'content-type':'application/json'}:{}),...(csrf?{'x-csrf-token':csrf}:{}),...init.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new BffError(response.status,typeof body.error==='string'?body.error:'Request failed safely');if(typeof body.csrfToken==='string')csrf=body.csrfToken;return body as T}
export async function bootstrap(){try{return await request<BffStatus>('/api/status')}catch(error){if(!(error instanceof BffError)||error.status!==401)throw error;await request('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});return request<BffStatus>('/api/status')}}
export const bff={status:()=>request<BffStatus>('/api/status'),connect:async(cleanup=false)=>{const result=await request<{authorizationUrl:string}>('/api/oauth/start',{method:'POST',body:JSON.stringify({cleanup})});location.assign(result.authorizationUrl)},sync:()=>request<{messages:GmailMetadata[]}>('/api/sync',{method:'POST',body:'{}'}),messages:()=>request<{messages:GmailMetadata[]}>('/api/messages'),protections:()=>request<ProtectionState>('/api/protections'),protect:(senders:string[],domains:string[],expectedVersion:number)=>request<ProtectionState>('/api/protections',{method:'PUT',body:JSON.stringify({senders,domains,expectedVersion})}),addProtectedSenders:(senders:string[])=>request<ProtectionState>('/api/protections/senders',{method:'POST',body:JSON.stringify({senders})}),preview:(action:'trash'|'restore',ids:string[])=>request<ServerPreview>('/api/previews',{method:'POST',body:JSON.stringify({action,ids})}),execute:(previewId:string,confirmation?:string)=>request<JobResult>('/api/jobs',{method:'POST',headers:{'idempotency-key':crypto.randomUUID()},body:JSON.stringify({previewId,confirmation})}),activity:()=>request<{events:ServerAuditEvent[]}>('/api/activity'),disconnect:()=>request('/api/disconnect',{method:'POST',body:'{}'}),deleteData:()=>request('/api/account',{method:'DELETE',body:'{}'}),
  brands:()=>request<{brands:BrandSummary[]}>('/api/brands'),
  categories:()=>request<{categories:CategoryDescriptor[]}>('/api/categories'),
  brandDetail:(brandKey:string)=>request<BrandDetail>(`/api/brands/${encodeURIComponent(brandKey)}`),
  renameBrand:(brandKey:string,displayName:string)=>request<{brandKey:string;displayName:string;isCustom:boolean}>(`/api/brands/${encodeURIComponent(brandKey)}/rename`,{method:'POST',body:JSON.stringify({displayName})}),
  previewByBrand:(brandKey:string,category?:string)=>request<ServerPreview>('/api/cleanups/preview',{method:'POST',body:JSON.stringify({brandKey,category})})};